version: '3'

services:
  prometheus:
    image: {{ prometheus_docker_image }}
    restart: always

    {% if prometheus_docker_ports %}

    ports:
      {% for port in prometheus_docker_ports -%}
      - "{{ port }}"
      {% endfor %}
    {% endif %}

    volumes:
      - ./cfg/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data:/prometheus
    labels:
      - traefik.http.routers.prometheus.rule=Host(`prometheus.{{ domain }}`)
      {% if https -%}
      - traefik.http.routers.prometheus-unsecure.rule=Host(`prometheus.{{ domain }}`)
      - traefik.http.routers.prometheus-unsecure.middlewares=force_https
      - traefik.http.routers.prometheus.tls=true
      {% if letsencrypt_certificate -%}
      - traefik.http.routers.prometheus.tls.certresolver=le
      {%- endif -%}
      {%- endif %}
      
    networks:
      {% for network in prometheus_docker_networks -%}
      - {{ network }}
      {% endfor %}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/-/healthy"]

networks:
  {% for network in prometheus_docker_networks -%}
  {{ network }}:
    external: true
  {% endfor %}